from Base_clases import *


class Main(IO):
    def __init__(self):
        super().__init__()
        self.a: Int = Int(0)
        self.b: Int = Int(0)
        self.c: Int = Int(0)

        self.a: Int = Int(2)
        self.b: Int = Int(1)
        self.c: Int = Int(3)

    @mutable_params
    def main(self, ) -> 'Object':
        def _block1():
            _bin3 = (self.b * self.a)

            _bin4 = (self.a + (self.b * ((self.a + (self.b * self.a)) + (self.b * (self.a + (self.b * ((self.a + (self.b * self.a)) + (self.b * (self.a + (self.b * ((self.a + (self.b * self.a)) + (self.b * (self.a + (self.b * ((self.a + (self.b * self.a)) + (self.b * (self.a + (self.b * ((self.a + (self.b * self.a)) + (self.b * (self.a + (self.b * ((self.a + (self.b * self.a)) + (self.b * (self.a + (self.b * ((self.a + (self.b * self.a)) + (self.b * (self.a + (self.b * ((self.a + (self.b * self.a)) + (self.b * (self.a + (self.b * ((self.a + (self.b * self.a)) + (self.b * (self.a + (self.b * ((self.a + (self.b * self.a)) + (self.b * (self.a + (self.b * ((self.a + (self.b * self.a)) + (self.b * (self.a + (self.b * ((self.a + (self.b * self.a)) + (self.b * (self.a + (self.b * ((self.a + (self.b * self.a)) + (self.b * (self.a + (self.b * ((self.a + (self.b * self.a)) + (self.b * (self.a + (self.b * ((self.a + (self.b * self.a)) + (self.b * (self.a + (self.b * ((self.a + (self.b * self.a)) + (self.b * (self.a + (self.b * ((self.a + (self.b * self.a)) + (self.b * (self.a + (self.b * ((self.a + (self.b * self.a)) + (self.b * (self.a + (self.b * ((self.a + (self.b * self.a)) + (self.b * (self.a + (self.b * ((self.a + (self.b * self.a)) + (self.b * (self.a + (self.b * (self.a + (self.b * self.c))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))

            _bin2 = (self.b * ((self.a + (self.b * self.a)) + (self.b * (self.a + (self.b * ((self.a + (self.b * self.a)) + (self.b * (self.a + (self.b * ((self.a + (self.b * self.a)) + (self.b * (self.a + (self.b * ((self.a + (self.b * self.a)) + (self.b * (self.a + (self.b * ((self.a + (self.b * self.a)) + (self.b * (self.a + (self.b * ((self.a + (self.b * self.a)) + (self.b * (self.a + (self.b * ((self.a + (self.b * self.a)) + (self.b * (self.a + (self.b * ((self.a + (self.b * self.a)) + (self.b * (self.a + (self.b * ((self.a + (self.b * self.a)) + (self.b * (self.a + (self.b * ((self.a + (self.b * self.a)) + (self.b * (self.a + (self.b * ((self.a + (self.b * self.a)) + (self.b * (self.a + (self.b * ((self.a + (self.b * self.a)) + (self.b * (self.a + (self.b * ((self.a + (self.b * self.a)) + (self.b * (self.a + (self.b * ((self.a + (self.b * self.a)) + (self.b * (self.a + (self.b * ((self.a + (self.b * self.a)) + (self.b * (self.a + (self.b * ((self.a + (self.b * self.a)) + (self.b * (self.a + (self.b * ((self.a + (self.b * self.a)) + (self.b * (self.a + (self.b * ((self.a + (self.b * self.a)) + (self.b * (self.a + (self.b * ((self.a + (self.b * self.a)) + (self.b * (self.a + (self.b * ((self.a + (self.b * self.a)) + (self.b * (self.a + (self.b * ((self.a + (self.b * self.a)) + (self.b * (self.a + (self.b * ((self.a + (self.b * self.a)) + (self.b * (self.a + (self.b * ((self.a + (self.b * self.a)) + (self.b * (self.a + (self.b * ((self.a + (self.b * self.a)) + (self.b * (self.a + (self.b * ((self.a + (self.b * self.a)) + (self.b * (self.a + (self.b * ((self.a + (self.b * self.a)) + (self.b * (self.a + (self.b * ((self.a + (self.b * self.a)) + (self.b * (self.a + (self.b * ((self.a + (self.b * self.a)) + (self.b * (self.a + (self.b * ((self.a + (self.b * self.a)) + (self.b * (self.a + (self.b * ((self.a + (self.b * self.a)) + (self.b * (self.a + (self.b * (self.a + (self.b * (self.a + (self.b * ((self.a + (self.b * self.a)) + (self.b * (self.a + (self.b * ((self.a + (self.b * self.a)) + (self.b * (self.a + (self.b * ((self.a + (self.b * self.a)) + (self.b * (self.a + (self.b * ((self.a + (self.b * self.a)) + (self.b * (self.a + (self.b * ((self.a + (self.b * self.a)) + (self.b * (self.a + (self.b * ((self.a + (self.b * self.a)) + (self.b * (self.a + (self.b * ((self.a + _bin3) + (self.b * _bin4)))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))

            _bin1 = ((self.a + (self.b * self.a)) + (self.b * (self.a + (self.b * (self.a + (self.b * (self.a + (self.b * ((self.a + (self.b * self.a)) + (self.b * (self.a + (self.b * ((self.a + (self.b * self.a)) + (self.b * (self.a + (self.b * ((self.a + (self.b * self.a)) + (self.b * (self.a + (self.b * ((self.a + (self.b * self.a)) + (self.b * (self.a + (self.b * ((self.a + (self.b * self.a)) + (self.b * (self.a + (self.b * ((self.a + (self.b * self.a)) + (self.b * (self.a + (self.b * ((self.a + (self.b * self.a)) + (self.b * (self.a + (self.b * ((self.a + (self.b * self.a)) + (self.b * (self.a + (self.b * ((self.a + (self.b * self.a)) + (self.b * (self.a + (self.b * ((self.a + (self.b * self.a)) + (self.b * (self.a + (self.b * ((self.a + (self.b * self.a)) + (self.b * (self.a + (self.b * ((self.a + (self.b * self.a)) + (self.b * (self.a + (self.b * ((self.a + (self.b * self.a)) + (self.b * (self.a + (self.b * ((self.a + (self.b * self.a)) + (self.b * (self.a + (self.b * ((self.a + (self.b * self.a)) + (self.b * (self.a + (self.b * ((self.a + (self.b * self.a)) + (self.b * (self.a + (self.b * ((self.a + (self.b * self.a)) + (self.b * (self.a + (self.b * ((self.a + (self.b * self.a)) + (self.b * (self.a + (self.b * ((self.a + (self.b * self.a)) + (self.b * (self.a + (self.b * ((self.a + (self.b * self.a)) + (self.b * (self.a + (self.b * ((self.a + (self.b * self.a)) + (self.b * (self.a + (self.b * ((self.a + (self.b * self.a)) + (self.b * (self.a + (self.b * ((self.a + (self.b * self.a)) + (self.b * (self.a + (self.b * ((self.a + (self.b * self.a)) + (self.b * (self.a + (self.b * ((self.a + (self.b * self.a)) + (self.b * (self.a + (self.b * ((self.a + (self.b * self.a)) + (self.b * (self.a + (self.b * ((self.a + (self.b * self.a)) + (self.b * (self.a + (self.b * ((self.a + (self.b * self.a)) + (self.b * (self.a + (self.b * ((self.a + (self.b * self.a)) + (self.b * (self.a + (self.b * ((self.a + (self.b * self.a)) + (self.b * (self.a + (self.b * ((self.a + (self.b * self.a)) + (self.b * (self.a + (self.b * ((self.a + (self.b * self.a)) + (self.b * (self.a + (self.b * ((self.a + (self.b * self.a)) + (self.b * (self.a + (self.b * ((self.a + (self.b * self.a)) + (self.b * (self.a + (self.b * ((self.a + (self.b * self.a)) + (self.b * (self.a + (self.b * ((self.a + (self.b * self.a)) + (self.b * (self.a + _bin2)))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))

            self.out_int((self.a + (self.b * ((self.a + (self.b * self.a)) + (self.b * (self.a + (self.b * ((self.a + (self.b * self.a)) + (self.b * (self.a + (self.b * ((self.a + (self.b * self.a)) + (self.b * (self.a + (self.b * ((self.a + (self.b * self.a)) + (self.b * (self.a + (self.b * ((self.a + (self.b * self.a)) + (self.b * (self.a + (self.b * ((self.a + (self.b * self.a)) + (self.b * (self.a + (self.b * ((self.a + (self.b * self.a)) + (self.b * (self.a + (self.b * ((self.a + (self.b * self.a)) + (self.b * (self.a + (self.b * ((self.a + (self.b * self.a)) + (self.b * (self.a + (self.b * ((self.a + (self.b * self.a)) + (self.b * (self.a + (self.b * ((self.a + (self.b * self.a)) + (self.b * (self.a + (self.b * ((self.a + (self.b * self.a)) + (self.b * (self.a + (self.b * ((self.a + (self.b * self.a)) + (self.b * (self.a + (self.b * ((self.a + (self.b * self.a)) + (self.b * (self.a + (self.b * ((self.a + (self.b * self.a)) + (self.b * (self.a + (self.b * ((self.a + (self.b * self.a)) + (self.b * (self.a + (self.b * ((self.a + (self.b * self.a)) + (self.b * (self.a + (self.b * ((self.a + (self.b * self.a)) + (self.b * (self.a + (self.b * ((self.a + (self.b * self.a)) + (self.b * (self.a + (self.b * ((self.a + (self.b * self.a)) + (self.b * (self.a + (self.b * ((self.a + (self.b * self.a)) + (self.b * (self.a + (self.b * ((self.a + (self.b * self.a)) + (self.b * (self.a + (self.b * ((self.a + (self.b * self.a)) + (self.b * (self.a + (self.b * ((self.a + (self.b * self.a)) + (self.b * (self.a + (self.b * ((self.a + (self.b * self.a)) + (self.b * (self.a + (self.b * ((self.a + (self.b * self.a)) + (self.b * (self.a + (self.b * ((self.a + (self.b * self.a)) + (self.b * (self.a + (self.b * ((self.a + (self.b * self.a)) + (self.b * (self.a + (self.b * ((self.a + (self.b * self.a)) + (self.b * (self.a + (self.b * ((self.a + (self.b * self.a)) + (self.b * (self.a + (self.b * ((self.a + (self.b * self.a)) + (self.b * (self.a + (self.b * ((self.a + (self.b * self.a)) + (self.b * (self.a + (self.b * ((self.a + (self.b * self.a)) + (self.b * (self.a + (self.b * ((self.a + (self.b * self.a)) + (self.b * (self.a + (self.b * ((self.a + (self.b * self.a)) + (self.b * (self.a + (self.b * ((self.a + (self.b * self.a)) + (self.b * (self.a + (self.b * ((self.a + (self.b * self.a)) + (self.b * (self.a + (self.b * _bin1)))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))
            return self.out_string(String("\n"))

        return _block1()

    def copy(self):
        c = Main()
        c.a = self.a
        c.b = self.b
        c.c = self.c
        return c

if __name__ == '__main__':
    bootstrap(Main)
